const fs = require('fs');
let c = fs.readFileSync('./src/app/page.tsx', 'utf8');

c = c.replace(/Research Bitcoin/g, '研究比特幣投資機會');
c = c.replace(/Analyze BTC market/g, '分析比特幣市場');
c = c.replace(/FIRE Review/g, 'FIRE組合review');
c = c.replace(/Weekly portfolio review/g, '每週檢視投資組合表現');
c = c.replace(/Baby Checklist/g, '寶寶用品清單');
c = c.replace(/Newborn essentials/g, '整理初生嬰兒所需物品');
c = c.replace(/Investment/g, '投資');
c = c.replace(/Family/g, '家庭');
c = c.replace(/System/g, '系統');
c = c.replace(/Bitcoin Analysis Done/g, '比特幣投資分析完成');
c = c.replace(/Complete BTC research.*allocation/g, '完成比特幣投資機會研究，報告已存檔。建議配置3-5%資產');
c = c.replace(/Mission Control Launch/g, 'Mission Control系統建立');
c = c.replace(/Built Mission Control Dashboard/g, '建立Mission Control儀表板');
c = c.replace(/Task Done/g, '完成任務');
c = c.replace(/Bitcoin report completed/g, '比特幣投資研究報告已完成並存檔');
c = c.replace(/Memory Added/g, '新增記憶');
c = c.replace(/Recorded BTC conclusions/g, '記錄比特幣投資分析結論');
c = c.replace(/System Built/g, '建立系統');
c = c.replace(/Created Mission Control/g, '創建Mission Control儀表板');
c = c.replace(/Weekly Portfolio Review/g, '每週投資組合review');
c = c.replace(/BTC Price Check/g, '比特幣價格檢查');
c = c.replace(/Bitcoin/g, '比特幣');
c = c.replace(/Total Assets/g, '總資產');
c = c.replace(/24h Change/g, '24小時變動');
c = c.replace(/Holdings/g, '持倉數量');
c = c.replace(/Cash Level/g, '現金水平');
c = c.replace(/Recent Activities/g, '最近活動');
c = c.replace(/Daily Brief/g, '每日簡報');
c = c.replace(/Tasks Today/g, '今日任務');
c = c.replace(/Schedule/g, '日程');
c = c.replace(/Search memories/g, '搜尋記憶');
c = c.replace(/Search tasks.*activities/g, '搜尋任務、記憶、活動');
c = c.replace(/To Do/g, '待完成');

fs.writeFileSync('./src/app/page.tsx', c, 'utf8');
console.log('Done!');
